name: lightAshura
author: lightPlugins
description: Plugin exclusive for ASHURAMC
website: ashuramc.de
version: 1.0.0
main: de.lightplugins.master.Ashura
api-version: 1.20
depend: [Vault]
softdepend: [PlaceholderAPI, EcoItems]
loadbefore: [Essentials]
commands: {
  a:
}