name: lightAshura
author: lightPlugins
description: Plugin exclusive for ASHURAMC
website: ashuramc.de
version: 1.0.0
main: de.lightplugins.master.Ashura
api-version: 1.20
depend: [Vault]
softdepend: [PlaceholderAPI, WorldGuard, EcoItems, Eco, eco, EcoJobs, MythicMobs]
loadbefore: [Essentials]
commands:
  a:
    description: Set the time of the current world to day
  day:
    description: Set the time to day with animation
  night:
    description: Set the time to night with animation
  gmc:
    description: Set the gamemode to creative
  gms:
    description: Set the gamemode to survival
  speed:
    description: Change the fly and walk speed
  h:
    description: restore hunger and health
  sun:
    description: Change the fly and walk speed
  tutorial:
    description: Opens the server guide
  discord:
    description: Opens the server guide
    aliases: [dc]
  karte:
    description: Opens the server guide
  trash:
    description: Opens the trash can
    aliases: [mülleimer]