mysql:
  # if disabled, the plugin will use automatically sqlite for single server setup
  enable: false
  host: 127.0.0.1
  port: 3306
  database: databaseName
  user: username
  password: YourSecretPassword
  ssl: false
  advanced:
    # Don't change any values here if you don't know what you're doing
    connectionPoolSize: 10
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    cachePrepStmts: true
    useServerPrepStmts: true
settings:
  skyhunt:
    enable: false
  onServerJoin:
    commands:
      enable: true
      list:
#         command;executedAs;delayInTicks
        - 'ecoitems give #player-name# beginner_axe;console;20'
        - 'ecoitems give #player-name# beginner_pickaxe;console;20'
        - 'ecoitems give #player-name# beginner_shovel;console;20'
        - 'ecoitems give #player-name# beginner_sword;console;20'
        - 'ecoarmor give #player-name# set:beginner;console;20'
    message:
      enable: true
      test:
        - ''
        - ' Das ist ein toller Server'
        - ''
  worldGuard:
    # Generiert nach erfolgreichem Welten laden folgende Flags
    generateWorldGuardFlagsOnInit:
      worlds:
        [0]:
          world: 'NaturGrotte_'
          craftingTableUse: deny
          passthrough: deny
          use: allow
          chestAccess: allow
  spawnOnJoin:
    enable: false
    command: 'warp lobby #playername#'
  starterBox:
    enable: false
    boxID: 'starterPack'
