stages:
  '1':  # NUR Zahlen von 1-99 !!!
    schematic: stage-1
    armorStandName: 'spawn' # Der name den der Armorstand auf der Template island hat
    mythicMobType: SHEEP
    killsForNextStage: 800
    neededPermission: 'lightashura.skyhunt.stage.1'
    lootTable: 'stage-1'